language: node_js
node_js:
  - "stable"
    
sudo: required

branches:
  only:
    - firestore

before_script:
  - npm install -g firebase-tools
  - npm install -g ionic
  - npm install -g cordova

script:
  - ionic build --platform browser

